### ISSUE TITLE
Placing the sun in the sky

### ISSUE THREAD

**Issue by mallman** [Esri/arcgis-maps-sdk-swift#11]
Hello,

Is it possible to place the sun in the sky in a `SceneView`? I can see there's an API for specifying a "sun date": https://developers.arcgis.com/swift/api-reference/documentation/arcgis/sceneview/sundate(_:). I believe this affects some kind of shadow rendering on topography. However, I don't see a straightforward way to place the sun in the sky in a time/view accurate location. For example, I'm looking for a capability like what's possible with Google Earth Pro's sun visualization.

Cheers.

**Comment by koushikhajra01** [comment]
Hello @mallman Thank you for reaching out to us with your query. It is not possible at the moment to place the sun in the sky in a SceneView. We will support it in a future release. With the [sundate](https://developers.arcgis.com/swift/api-reference/documentation/arcgis/sceneview/sundate(_:)) api that you alluded to, it is mainly to cast shadows and by setting date and time. You will need to enable [sunlighting](https://developers.arcgis.com/swift/api-reference/documentation/arcgis/sceneview/sunlighting(_:)) first. 

Please let us know if you have further questions.

**Comment by mallman** [comment]
Thanks for the clarification!
