### ISSUE TITLE
Connect to own server

### ISSUE THREAD

**Issue by nicop2000** [Esri/arcgis-maps-sdk-swift#13]
Hi there,
is it possible to connect to a own instance of an ArcGIS Server with this package and if so, how would one do this?

With own instance I am referring to a setup server with own collected map data. This ArcGIS Server already exists. I don't want to use the given data from Esri where you need these API Keys mentioned in the tutorial

Thanks in advance

**Comment by njarecha** [comment]
Yes, you can use the layers/services from your ArcGIS server. You should create a layer object based on type of service, create a `Basemap` with the layer and then a map with a basemap. Here is the example code which uses the `ArcGISMapImageLayer` which can be created with a `Map Service URL`.

```
let layer = ArcGISMapImageLayer(url: <map service url>)
let basemap = Basemap(baseLayer: layer)
let map = Map(basemap: basemap)
```
