### ISSUE TITLE
Kotlin Multiplatform support

### ISSUE THREAD

**Issue by orelvis15** [Esri/arcgis-maps-sdk-swift#18]
In my company we are migrating current apps to multiplatform Kotlin test versions.

Currently kotlin multiplatform does not support SPM, they only maintain integration with cocoapods.

Would it be possible to upload these dependencies to cocoapods?, or implement a multiplatform Kotlin library to use directly in the projects.

I'm waiting for the answer. greetings.

**Comment by zkline101** [comment]
Hello,

Thank you for the feedback. We don't have plans to add support for cocoapods.

Thank you.

**Comment by zkline101** [comment]
Also, just a heads up we have a [forum](https://community.esri.com/t5/swift-maps-sdk-questions/bd-p/swift-maps-sdk-questions) for this product which would be the best place to ask questions. Thank you!
