### ISSUE TITLE
Add support for cocapods

### ISSUE THREAD

**Issue by JulianBissekkou** [Esri/arcgis-maps-sdk-swift#19]
We are maitaining the [arcigs_map_sdk](https://github.com/fluttercommunity/arcgis_map_sdk) flutter package and we would like to use the latest 200 release.

Flutter and also [Kotlin Multiplatform](https://github.com/Esri/arcgis-maps-sdk-swift/issues/18) do not support SPM at the moment, therefore a release in cocapods would be very nice.

**Comment by rolson** [comment]
At this point there are no plans to support distribution via cocoapods. Also, we do have a beta program for an [Esri ArcGIS Maps SDK for Flutter](https://www.esri.com/arcgis-blog/products/developers/announcements/announcing-arcgis-maps-sdk-for-flutter-beta/).

**Comment by JulianBissekkou** [comment]
@rolson 
Will the flutter sdk be open source?
Do you know if the flutter sdk will support web as well?

**Comment by rolson** [comment]
@JulianBissekkou if you have questions about the Flutter SDK it's best to engage through the beta program.
