### ISSUE TITLE
Package arcgis-maps-sdk-swift 200.2.0 not working

### ISSUE THREAD

**Issue by bux225** [Esri/arcgis-maps-sdk-swift#9]
I am following the first tutorial (Display a Map) to the letter: https://developers.arcgis.com/swift/maps-2d/tutorials/display-a-map/

At the completion of "Set your API Key" step 4 when I build and run it fails with several errors.

On "import ArcGIS" lines soon MainApp and ContentView I get a warning that "File "MainApp.swift" is part of module "ArcGIS". Ignoring import"

Thus I get error on MainApp:
* Cannot find "APIKey" in scope
* Cannot find "ArcGISEnvironment" in scope

On ContentView:
* Cannot find "Map" in scope
* Cannot find "MapView" in scope

If I remove all ArcGIS-specific code from MainApp and ContentView, but leave package attached and build run, I get the following on the terminal:

warning: (arm64) /Users/......../Xcode/DerivedData/ArcGIS-hjnpakqxnfpnyhampxhiyvbreuev/Build/Products/Debug-iphonesimulator/ArcGIS.app/Frameworks/CoreArcGIS.framework/CoreArcGIS empty dSYM file detected, dSYM was created with an executable with no debug info.

**Comment by dfeinzimer** [comment]
Hi @bux225, can you please confirm a few things?

1. In the Project Navigator under "Package Dependencies" you see the following:

<p align="center"><img width="260" alt="Package Dependencies" src="https://github.com/Esri/arcgis-maps-sdk-swift/assets/16397058/508a60a9-8766-4deb-b5e8-d8ac59e7292b"></pm>

2. In your app's target under "Frameworks, Libraries, and Embedded Content" you see the following:
 
<p align="center"><img width="323" alt="Frameworks Libraries and Embedded Content" src="https://github.com/Esri/arcgis-maps-sdk-swift/assets/16397058/2671b935-80e3-4beb-8134-73d0bc3207ff"></p>

3. In `MainApp.swift` you've set the type of `body` to `some SwiftUI.Scene`:

<p align="center"><img width="257" alt="Screenshot 2023-08-18 at 23 18 07" src="https://github.com/Esri/arcgis-maps-sdk-swift/assets/16397058/4227e76c-40c2-4ae4-8d24-75092b231385"></p>

**Comment by bux225** [comment]
Yes to all.

**Comment by dfeinzimer** [comment]
Hi @bux225, is it possible that when creating your new project "ArcGIS" was used as the Product Name? Doing so would cause a name collision with the SDK and trigger the same error you reported.

<img width="403" alt="Screenshot 2023-08-19 at 08 07 58" src="https://github.com/Esri/arcgis-maps-sdk-swift/assets/16397058/fee33f5d-1104-42b4-9a21-66b021dcda66">
<img width="560" alt="Screenshot 2023-08-19 at 08 11 29" src="https://github.com/Esri/arcgis-maps-sdk-swift/assets/16397058/471e2359-f010-4731-acbf-3a9781cf650d">

**Comment by bux225** [comment]
Oh, for the love of Pete.  My fault. Sorry for the bother.

**Comment by dfeinzimer** [comment]
Glad we were able to get to the bottom of it!
